
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests: 
      storage: 40Gi
  storageClassName: do-block-storage ### digitalocean block storage