apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-volume-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-volume-app
  template:
    metadata:
      labels:
        app: shared-volume-app
    spec:
      containers:
      - name: writer
        image: busybox
        command: []
        volumeMounts:
        - name: shared-data
          mountPath: "/data"
      - name: reader
        image: busybox
        command: []
        volumeMounts:
        - name: shared-data
          mountPath: "/data"

      volumes:
      - name: shared-data
        emptyDir: {}