# my-values.yaml
auth:
  enabled: true
  rootPassword: "secretpassword"
  username: "me"
  password: "mypassword"
  database: "myapp"

replicaCount: 1

resources:
  requests:
    cpu: "300m"       # changed from 250m
    memory: "512Mi"   # changed from 256Mi
  limits:
    cpu: "600m"       # changed from 500m
    memory: "768Mi"   # changed from 512Mi
persistence:
  enabled: true
  size: "2Gi"